name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggered every time you push to the main branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        # This tells npm to ignore the version conflict between Angular 19 and 21
        run: npm install --legacy-peer-deps

      - name: Build Angular App
        # Ensure the build command also uses the same flag if needed
        run: npx ng build --configuration production --base-href /QIM/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/qim/browser # Path to your build folder
          branch: gh-pages # The branch the built files will live on
